### ISSUE TITLE
IndexError while training

### ISSUE THREAD

**Issue by krmaxwell** [krmaxwell/megahal#1]
Training MegaHAL on my [tweets](/krmaxwell/tweets):

```
$ megahal -T tweets.txt
Traceback (most recent call last):
  File "/home/kmaxwell/src/megahal/venv/bin/megahal", line 27, in <module>
    sys.exit(main())
  File "/home/kmaxwell/src/megahal/venv/bin/megahal", line 21, in main
    megahal.train(opts.train)
  File "/home/kmaxwell/src/megahal/venv/local/lib/python2.7/site-packages/megahal.py", line 438, in train
    self.learn(line)
  File "/home/kmaxwell/src/megahal/venv/local/lib/python2.7/site-packages/megahal.py", line 442, in learn
    self.__brain.communicate(phrase, reply=False)
  File "/home/kmaxwell/src/megahal/venv/local/lib/python2.7/site-packages/megahal.py", line 207, in communicate
    words = self.get_words_from_phrase(phrase)
  File "/home/kmaxwell/src/megahal/venv/local/lib/python2.7/site-packages/megahal.py", line 192, in get_words_from_phrase
    if boundary(phrase, offset):
  File "/home/kmaxwell/src/megahal/venv/local/lib/python2.7/site-packages/megahal.py", line 172, in boundary
    string[position + 1].isalpha()):
IndexError: string index out of range
Closing database
```

**Comment by krmaxwell** [comment]
So line 172:

```
string[position + 1].isalpha()): 
```

Clearly if we're at the end of string, this is out of range. Adding a quick length check.
